#!/usr/bin/env zsh

NODE_VERSION=$(node -v)

[[ "${NODE_VERSION:0:2}" == "v8" ]] || {
  # gulp crashes with higher versions https://github.com/gulpjs/gulp/issues/2162
  echo "building requires Node v8.x.x"
  exit 1
}

ROOT=$(pwd)

npm run handlebars && gulp && npm run update-spec

renameFileWithCacheBuster(){
  basePath=$1
  fileName=$2
  ext=$3
  fileBase="${1}/${2}"
  filePath="${1}/${2}.${ext}"
  fileHash=$(md5sum $filePath |cut -c 1-7)
  filePathWithHash="${fileBase}.${fileHash}.${ext}"
  mv $filePath $filePathWithHash
  gzip -k9 $filePathWithHash
  sed -i "s/${fileName}.${ext}/${fileName}.${fileHash}.${ext}/" dist/index.html
}

# CSS
# Couldn't make concatenated CSS files work
# But it's fine as they are used for different media
renameFileWithCacheBuster 'dist/css' 'typography' 'css'
renameFileWithCacheBuster 'dist/css' 'reset' 'css'
renameFileWithCacheBuster 'dist/css' 'screen' 'css'
renameFileWithCacheBuster 'dist/css' 'print' 'css'

# JS
mkdir -p dist/js
jsBuildBase=dist/js/build

addJsFile(){
  cat $1 >> ${jsBuildBase}.js
  printf ";" >> ${jsBuildBase}.js
}

addJsFile dist/lib/object-assign-pollyfill.js
addJsFile dist/lib/jquery-1.8.0.min.js
addJsFile dist/lib/jquery.slideto.min.js
addJsFile dist/lib/jquery.wiggle.min.js
addJsFile dist/lib/jquery.ba-bbq.min.js
addJsFile dist/lib/handlebars-4.7.1.js
addJsFile dist/lib/lodash.min.js
addJsFile dist/lib/backbone-min.js
addJsFile dist/swagger-ui.min.js
addJsFile dist/lib/highlight.9.1.0.pack.js
addJsFile dist/lib/highlight.9.1.0.pack_extended.js
addJsFile dist/lib/jsoneditor.min.js
addJsFile dist/lib/marked.js
addJsFile dist/lib/swagger-oauth.js

renameFileWithCacheBuster 'dist/js' 'build' 'js'
