#!/usr/bin/env zsh
npm run handlebars && gulp &&
cat src/swagger.json | scripts/uglify_json.js > dist/swagger.json

addFile(){
  cat $1 >> $2
  echo ";" >> $2
}

renameFileWithCacheBuster(){
  fileBase=$1
  ext=$2
  fileHash=$(md5sum $fileBase |cut -c 1-7)
  filePath=$(echo "${fileBase}.${fileHash}.${ext}")
  mv $fileBase $filePath
  gzip -k9 $filePath
  sed -i "s/build.${ext}/build.${fileHash}.${ext}/" dist/index.html
}

# CSS
cssBuildBase=dist/css/build
rm -f dist/css/build*

addFile dist/css/typography.css $cssBuildBase
addFile dist/css/reset.css $cssBuildBase
addFile dist/css/screen.css $cssBuildBase
addFile dist/css/reset.css $cssBuildBase
addFile dist/css/print.css $cssBuildBase

renameFileWithCacheBuster $cssBuildBase 'css'

# JS
jsBuildBase=dist/build
rm -f dist/build*

addFile dist/lib/object-assign-pollyfill.js $jsBuildBase
addFile dist/lib/jquery-1.8.0.min.js $jsBuildBase
addFile dist/lib/jquery.slideto.min.js $jsBuildBase
addFile dist/lib/jquery.wiggle.min.js $jsBuildBase
addFile dist/lib/jquery.ba-bbq.min.js $jsBuildBase
addFile dist/lib/handlebars-4.0.5.js $jsBuildBase
addFile dist/lib/lodash.min.js $jsBuildBase
addFile dist/lib/backbone-min.js $jsBuildBase
addFile dist/swagger-ui.min.js $jsBuildBase
addFile dist/lib/highlight.9.1.0.pack.js $jsBuildBase
addFile dist/lib/highlight.9.1.0.pack_extended.js $jsBuildBase
addFile dist/lib/jsoneditor.min.js $jsBuildBase
addFile dist/lib/marked.js $jsBuildBase
addFile dist/lib/swagger-oauth.js $jsBuildBase

renameFileWithCacheBuster $jsBuildBase 'js'
